### ISSUE TITLE
Special characters not properly displayed

### ISSUE THREAD

**Issue by titansmc** [e-user/50shades#2] opened 2019-10-18 10:11 UTC
Hi,
I see that logs from Graylog are fine, but when I use the tool I see "&quot" and those sort of characters.
 
```
[k1n01.domain.com] time=&quot;2019-10-18T10:08:15Z&quot; level=debug msg=&quot;
```

**Comment by outergod** [comment] 2019-10-19 15:25
I'll look into it.

**Comment by outergod** [comment] 2019-10-19 15:45
@titansmc so the problem is that the default template uses `{{}}` syntax which performs html encoding on the message, so it should be `{{{}}}`, i.e. three brackets instead of one, instead. While the commit referenced above fixes the issue for the default parameter, you can already have the issue worked around for yourself by specifying

```toml
[templates]
default = '[{{default container_name "-"}}] {{{message}}}'
```

in your `config.toml`.

**Comment by titansmc** [comment] 2019-10-19 15:47
Cool, thanks. It would also be nice if you can paste the instructions on
how to build the binary.

**Comment by outergod** [comment] 2019-10-21 09:59
For the workaround, you actually don't need a new binary but just the configuration change.

If you would still like to build the binary yourself, please make yourself comfortable with Rust development. Documenting this is out of scope for this project, and the existing Rust documentation is quite exhaustive. This is a great starting point: https://www.rust-lang.org/learn/get-started
Once you have the toolchain up and running, all you need to do is issue `cargo build --release` to build a new release binary, the rest is automatic. I will consider adding this piece of information to the README.

**Closed as completed** 2019-10-29 15:06 UTC
